"""create_tenant_table

Revision ID: dc13605bcad1
Revises: 
Create Date: 2026-03-17 12:42:45.243104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc13605bcad1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_type', sa.Enum('IT', 'FINANCE', 'HEALTHCARE', 'EDUCATION', 'ECOMMERCE', 'MARKETING', 'CONSULTING', 'MANUFACTURING', name='companytype'), nullable=False),
    sa.Column('company_size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE', name='companysize'), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invite_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_tenants_invite_code'), 'tenants', ['invite_code'], unique=True)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_invite_code'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
